[Unit]
Wants=helix-voice-process-test.service
After=helix-voice-process-test.service

[Service]
SupplementaryGroups=helix-voice
Environment=XLX_HELIX_MODE=process
Environment=XLX_HELIX_SOCKET=/run/helix-voice/pcm.sock
Environment=XLX_HELIX_TIMEOUT_MS=5
