#!/usr/bin/env bash

save_configuration(){
  mkdir -p "$CONFIG_DIR" "$STATE_DIR" "$LOG_DIR"
  chmod 700 "$CONFIG_DIR" "$STATE_DIR" "$LOG_DIR"
  local target="$CONFIG_DIR/reflector.conf"
  cat > "$target" <<EOF
LANGUAGE='$LANGUAGE'
REFLECTOR_NUMBER='$REFLECTOR_NUMBER'
REFLECTOR_ID='$REFLECTOR_ID'
PUBLIC_NAME='${PUBLIC_NAME//\'/}'
DESCRIPTION='${DESCRIPTION//\'/}'
DOMAIN='${DOMAIN//\'/}'
SYSOP_CALLSIGN='${SYSOP_CALLSIGN//\'/}'
CONTACT_EMAIL='${CONTACT_EMAIL//\'/}'
LOCATION='${LOCATION//\'/}'
COUNTRY='${COUNTRY//\'/}'
TIMEZONE='${TIMEZONE//\'/}'
MODULES='${MODULES//\'/}'
ENABLE_DSTAR='$ENABLE_DSTAR'
ENABLE_DMR='$ENABLE_DMR'
ENABLE_YSF='$ENABLE_YSF'
ENABLE_NXDN='$ENABLE_NXDN'
ENABLE_P25='$ENABLE_P25'
ENABLE_M17='$ENABLE_M17'
INSTALL_ECHO='$INSTALL_ECHO'
ECHO_MODULE='${ECHO_MODULE:-}'
INSTALL_DASHBOARD='$INSTALL_DASHBOARD'
SHOW_SYSOP='$SHOW_SYSOP'
SHOW_LOCATION='$SHOW_LOCATION'
SHOW_EMAIL='$SHOW_EMAIL'
ENABLE_PWA='$ENABLE_PWA'
ENABLE_HTTPS='$ENABLE_HTTPS'
ENABLE_FIREWALL='$ENABLE_FIREWALL'
ENABLE_FAIL2BAN='$ENABLE_FAIL2BAN'
ENABLE_SECURITY_UPDATES='$ENABLE_SECURITY_UPDATES'
EOF
  chmod 600 "$target"
}
